-- Historical migration placeholder.
-- Version 202609210001 đã được ghi nhận trong migration history của remote.
-- Tài khoản demo hiện được quản lý bằng script: npm run seed:demo
-- Không seed tài khoản hoặc mật khẩu mẫu trong migration production.
